version: '3.8'
services:
  shadmin-api:
    container_name: shadmin
    image: shadmin:latest
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/shadmin-api/config/
      - ./static/:/shadmin-api/static/
      - ./temp/:/shadmin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge

