---
apiVersion: v1
kind: Service
metadata:
  name: shadmin
  labels:
    app: shadmin
    service: shadmin
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
  selector:
    app: shadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadmin-v1
  labels:
    app: shadmin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadmin
      version: v1
  template:
    metadata:
      labels:
        app: shadmin
        version: v1
    spec:
      containers:
      - name: shadmin
        image: registry.cn-shanghai.aliyuncs.com/shadmin-team/shadmin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shadmin
          mountPath: /temp
        - name: shadmin
          mountPath: /static
        - name: shadmin-config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: shadmin
        persistentVolumeClaim:
          claimName: shadmin
      - name: shadmin-config
        configMap:
          name: settings-admin
---
